//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AgencyRestAPI.mukiAgencyWR {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AgentProxySoap", Namespace="http://tempuri.org/")]
    public partial class AgentProxy : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AgencyRegistrationOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateAgencyRegistrationOperationCompleted;
        
        private System.Threading.SendOrPostCallback accountlistOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLoansOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMiniStatementOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetwithdrawableAccOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountBalanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAgentFloatOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAgentAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountExistOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAgentTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLoanStatementOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFosaStatementOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTransactionMinAmountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTransactionMaxAmountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTariffCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWithdrawalChargesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChargesOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostAgentTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostBranchAgentTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertMessagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertAgencyTransactionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AgentProxy() {
            this.Url = global::AgencyRestAPI.Properties.Settings.Default.AgencyRestAPI_mukiAgencyWR_AgentProxy;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AgencyRegistrationCompletedEventHandler AgencyRegistrationCompleted;
        
        /// <remarks/>
        public event UpdateAgencyRegistrationCompletedEventHandler UpdateAgencyRegistrationCompleted;
        
        /// <remarks/>
        public event accountlistCompletedEventHandler accountlistCompleted;
        
        /// <remarks/>
        public event GetLoansCompletedEventHandler GetLoansCompleted;
        
        /// <remarks/>
        public event GetAccountsCompletedEventHandler GetAccountsCompleted;
        
        /// <remarks/>
        public event GetMemberCompletedEventHandler GetMemberCompleted;
        
        /// <remarks/>
        public event GetMiniStatementCompletedEventHandler GetMiniStatementCompleted;
        
        /// <remarks/>
        public event GetAccountInfoCompletedEventHandler GetAccountInfoCompleted;
        
        /// <remarks/>
        public event GetwithdrawableAccCompletedEventHandler GetwithdrawableAccCompleted;
        
        /// <remarks/>
        public event GetAccountBalanceCompletedEventHandler GetAccountBalanceCompleted;
        
        /// <remarks/>
        public event GetAgentFloatCompletedEventHandler GetAgentFloatCompleted;
        
        /// <remarks/>
        public event GetAgentAccountCompletedEventHandler GetAgentAccountCompleted;
        
        /// <remarks/>
        public event GetAccountExistCompletedEventHandler GetAccountExistCompleted;
        
        /// <remarks/>
        public event GetAgentTransactionCompletedEventHandler GetAgentTransactionCompleted;
        
        /// <remarks/>
        public event GetLoanStatementCompletedEventHandler GetLoanStatementCompleted;
        
        /// <remarks/>
        public event GetFosaStatementCompletedEventHandler GetFosaStatementCompleted;
        
        /// <remarks/>
        public event GetTransactionMinAmountCompletedEventHandler GetTransactionMinAmountCompleted;
        
        /// <remarks/>
        public event GetTransactionMaxAmountCompletedEventHandler GetTransactionMaxAmountCompleted;
        
        /// <remarks/>
        public event GetTariffCodeCompletedEventHandler GetTariffCodeCompleted;
        
        /// <remarks/>
        public event GetWithdrawalChargesCompletedEventHandler GetWithdrawalChargesCompleted;
        
        /// <remarks/>
        public event GetChargesCompletedEventHandler GetChargesCompleted;
        
        /// <remarks/>
        public event PostAgentTransactionCompletedEventHandler PostAgentTransactionCompleted;
        
        /// <remarks/>
        public event PostBranchAgentTransactionCompletedEventHandler PostBranchAgentTransactionCompleted;
        
        /// <remarks/>
        public event InsertMessagesCompletedEventHandler InsertMessagesCompleted;
        
        /// <remarks/>
        public event InsertAgencyTransactionCompletedEventHandler InsertAgencyTransactionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgencyRegistration", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AgencyRegistration() {
            object[] results = this.Invoke("AgencyRegistration", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AgencyRegistrationAsync() {
            this.AgencyRegistrationAsync(null);
        }
        
        /// <remarks/>
        public void AgencyRegistrationAsync(object userState) {
            if ((this.AgencyRegistrationOperationCompleted == null)) {
                this.AgencyRegistrationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgencyRegistrationOperationCompleted);
            }
            this.InvokeAsync("AgencyRegistration", new object[0], this.AgencyRegistrationOperationCompleted, userState);
        }
        
        private void OnAgencyRegistrationOperationCompleted(object arg) {
            if ((this.AgencyRegistrationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgencyRegistrationCompleted(this, new AgencyRegistrationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateAgencyRegistration", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateAgencyRegistration(string acc) {
            object[] results = this.Invoke("UpdateAgencyRegistration", new object[] {
                        acc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAgencyRegistrationAsync(string acc) {
            this.UpdateAgencyRegistrationAsync(acc, null);
        }
        
        /// <remarks/>
        public void UpdateAgencyRegistrationAsync(string acc, object userState) {
            if ((this.UpdateAgencyRegistrationOperationCompleted == null)) {
                this.UpdateAgencyRegistrationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateAgencyRegistrationOperationCompleted);
            }
            this.InvokeAsync("UpdateAgencyRegistration", new object[] {
                        acc}, this.UpdateAgencyRegistrationOperationCompleted, userState);
        }
        
        private void OnUpdateAgencyRegistrationOperationCompleted(object arg) {
            if ((this.UpdateAgencyRegistrationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateAgencyRegistrationCompleted(this, new UpdateAgencyRegistrationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/accountlist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string accountlist(string id_no) {
            object[] results = this.Invoke("accountlist", new object[] {
                        id_no});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void accountlistAsync(string id_no) {
            this.accountlistAsync(id_no, null);
        }
        
        /// <remarks/>
        public void accountlistAsync(string id_no, object userState) {
            if ((this.accountlistOperationCompleted == null)) {
                this.accountlistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaccountlistOperationCompleted);
            }
            this.InvokeAsync("accountlist", new object[] {
                        id_no}, this.accountlistOperationCompleted, userState);
        }
        
        private void OnaccountlistOperationCompleted(object arg) {
            if ((this.accountlistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.accountlistCompleted(this, new accountlistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLoans", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLoans(string id_no) {
            object[] results = this.Invoke("GetLoans", new object[] {
                        id_no});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLoansAsync(string id_no) {
            this.GetLoansAsync(id_no, null);
        }
        
        /// <remarks/>
        public void GetLoansAsync(string id_no, object userState) {
            if ((this.GetLoansOperationCompleted == null)) {
                this.GetLoansOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLoansOperationCompleted);
            }
            this.InvokeAsync("GetLoans", new object[] {
                        id_no}, this.GetLoansOperationCompleted, userState);
        }
        
        private void OnGetLoansOperationCompleted(object arg) {
            if ((this.GetLoansCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLoansCompleted(this, new GetLoansCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAccounts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAccounts(string id_no) {
            object[] results = this.Invoke("GetAccounts", new object[] {
                        id_no});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountsAsync(string id_no) {
            this.GetAccountsAsync(id_no, null);
        }
        
        /// <remarks/>
        public void GetAccountsAsync(string id_no, object userState) {
            if ((this.GetAccountsOperationCompleted == null)) {
                this.GetAccountsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountsOperationCompleted);
            }
            this.InvokeAsync("GetAccounts", new object[] {
                        id_no}, this.GetAccountsOperationCompleted, userState);
        }
        
        private void OnGetAccountsOperationCompleted(object arg) {
            if ((this.GetAccountsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountsCompleted(this, new GetAccountsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMember", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMember(string id_no) {
            object[] results = this.Invoke("GetMember", new object[] {
                        id_no});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMemberAsync(string id_no) {
            this.GetMemberAsync(id_no, null);
        }
        
        /// <remarks/>
        public void GetMemberAsync(string id_no, object userState) {
            if ((this.GetMemberOperationCompleted == null)) {
                this.GetMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemberOperationCompleted);
            }
            this.InvokeAsync("GetMember", new object[] {
                        id_no}, this.GetMemberOperationCompleted, userState);
        }
        
        private void OnGetMemberOperationCompleted(object arg) {
            if ((this.GetMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemberCompleted(this, new GetMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMiniStatement", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMiniStatement(string acc) {
            object[] results = this.Invoke("GetMiniStatement", new object[] {
                        acc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMiniStatementAsync(string acc) {
            this.GetMiniStatementAsync(acc, null);
        }
        
        /// <remarks/>
        public void GetMiniStatementAsync(string acc, object userState) {
            if ((this.GetMiniStatementOperationCompleted == null)) {
                this.GetMiniStatementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMiniStatementOperationCompleted);
            }
            this.InvokeAsync("GetMiniStatement", new object[] {
                        acc}, this.GetMiniStatementOperationCompleted, userState);
        }
        
        private void OnGetMiniStatementOperationCompleted(object arg) {
            if ((this.GetMiniStatementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMiniStatementCompleted(this, new GetMiniStatementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAccountInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAccountInfo(string accNo) {
            object[] results = this.Invoke("GetAccountInfo", new object[] {
                        accNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountInfoAsync(string accNo) {
            this.GetAccountInfoAsync(accNo, null);
        }
        
        /// <remarks/>
        public void GetAccountInfoAsync(string accNo, object userState) {
            if ((this.GetAccountInfoOperationCompleted == null)) {
                this.GetAccountInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountInfoOperationCompleted);
            }
            this.InvokeAsync("GetAccountInfo", new object[] {
                        accNo}, this.GetAccountInfoOperationCompleted, userState);
        }
        
        private void OnGetAccountInfoOperationCompleted(object arg) {
            if ((this.GetAccountInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountInfoCompleted(this, new GetAccountInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetwithdrawableAcc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetwithdrawableAcc(string accNo) {
            object[] results = this.Invoke("GetwithdrawableAcc", new object[] {
                        accNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetwithdrawableAccAsync(string accNo) {
            this.GetwithdrawableAccAsync(accNo, null);
        }
        
        /// <remarks/>
        public void GetwithdrawableAccAsync(string accNo, object userState) {
            if ((this.GetwithdrawableAccOperationCompleted == null)) {
                this.GetwithdrawableAccOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetwithdrawableAccOperationCompleted);
            }
            this.InvokeAsync("GetwithdrawableAcc", new object[] {
                        accNo}, this.GetwithdrawableAccOperationCompleted, userState);
        }
        
        private void OnGetwithdrawableAccOperationCompleted(object arg) {
            if ((this.GetwithdrawableAccCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetwithdrawableAccCompleted(this, new GetwithdrawableAccCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAccountBalance", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal GetAccountBalance(string accNo) {
            object[] results = this.Invoke("GetAccountBalance", new object[] {
                        accNo});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountBalanceAsync(string accNo) {
            this.GetAccountBalanceAsync(accNo, null);
        }
        
        /// <remarks/>
        public void GetAccountBalanceAsync(string accNo, object userState) {
            if ((this.GetAccountBalanceOperationCompleted == null)) {
                this.GetAccountBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountBalanceOperationCompleted);
            }
            this.InvokeAsync("GetAccountBalance", new object[] {
                        accNo}, this.GetAccountBalanceOperationCompleted, userState);
        }
        
        private void OnGetAccountBalanceOperationCompleted(object arg) {
            if ((this.GetAccountBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountBalanceCompleted(this, new GetAccountBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAgentFloat", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal GetAgentFloat(string accNo) {
            object[] results = this.Invoke("GetAgentFloat", new object[] {
                        accNo});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void GetAgentFloatAsync(string accNo) {
            this.GetAgentFloatAsync(accNo, null);
        }
        
        /// <remarks/>
        public void GetAgentFloatAsync(string accNo, object userState) {
            if ((this.GetAgentFloatOperationCompleted == null)) {
                this.GetAgentFloatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAgentFloatOperationCompleted);
            }
            this.InvokeAsync("GetAgentFloat", new object[] {
                        accNo}, this.GetAgentFloatOperationCompleted, userState);
        }
        
        private void OnGetAgentFloatOperationCompleted(object arg) {
            if ((this.GetAgentFloatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAgentFloatCompleted(this, new GetAgentFloatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAgentAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAgentAccount(string code) {
            object[] results = this.Invoke("GetAgentAccount", new object[] {
                        code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAgentAccountAsync(string code) {
            this.GetAgentAccountAsync(code, null);
        }
        
        /// <remarks/>
        public void GetAgentAccountAsync(string code, object userState) {
            if ((this.GetAgentAccountOperationCompleted == null)) {
                this.GetAgentAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAgentAccountOperationCompleted);
            }
            this.InvokeAsync("GetAgentAccount", new object[] {
                        code}, this.GetAgentAccountOperationCompleted, userState);
        }
        
        private void OnGetAgentAccountOperationCompleted(object arg) {
            if ((this.GetAgentAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAgentAccountCompleted(this, new GetAgentAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAccountExist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAccountExist(string account, string code) {
            object[] results = this.Invoke("GetAccountExist", new object[] {
                        account,
                        code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountExistAsync(string account, string code) {
            this.GetAccountExistAsync(account, code, null);
        }
        
        /// <remarks/>
        public void GetAccountExistAsync(string account, string code, object userState) {
            if ((this.GetAccountExistOperationCompleted == null)) {
                this.GetAccountExistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountExistOperationCompleted);
            }
            this.InvokeAsync("GetAccountExist", new object[] {
                        account,
                        code}, this.GetAccountExistOperationCompleted, userState);
        }
        
        private void OnGetAccountExistOperationCompleted(object arg) {
            if ((this.GetAccountExistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountExistCompleted(this, new GetAccountExistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAgentTransaction", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAgentTransaction(string code) {
            object[] results = this.Invoke("GetAgentTransaction", new object[] {
                        code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAgentTransactionAsync(string code) {
            this.GetAgentTransactionAsync(code, null);
        }
        
        /// <remarks/>
        public void GetAgentTransactionAsync(string code, object userState) {
            if ((this.GetAgentTransactionOperationCompleted == null)) {
                this.GetAgentTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAgentTransactionOperationCompleted);
            }
            this.InvokeAsync("GetAgentTransaction", new object[] {
                        code}, this.GetAgentTransactionOperationCompleted, userState);
        }
        
        private void OnGetAgentTransactionOperationCompleted(object arg) {
            if ((this.GetAgentTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAgentTransactionCompleted(this, new GetAgentTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLoanStatement", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLoanStatement(string account, string LoanNo) {
            object[] results = this.Invoke("GetLoanStatement", new object[] {
                        account,
                        LoanNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLoanStatementAsync(string account, string LoanNo) {
            this.GetLoanStatementAsync(account, LoanNo, null);
        }
        
        /// <remarks/>
        public void GetLoanStatementAsync(string account, string LoanNo, object userState) {
            if ((this.GetLoanStatementOperationCompleted == null)) {
                this.GetLoanStatementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLoanStatementOperationCompleted);
            }
            this.InvokeAsync("GetLoanStatement", new object[] {
                        account,
                        LoanNo}, this.GetLoanStatementOperationCompleted, userState);
        }
        
        private void OnGetLoanStatementOperationCompleted(object arg) {
            if ((this.GetLoanStatementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLoanStatementCompleted(this, new GetLoanStatementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFosaStatement", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetFosaStatement(string account) {
            object[] results = this.Invoke("GetFosaStatement", new object[] {
                        account});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFosaStatementAsync(string account) {
            this.GetFosaStatementAsync(account, null);
        }
        
        /// <remarks/>
        public void GetFosaStatementAsync(string account, object userState) {
            if ((this.GetFosaStatementOperationCompleted == null)) {
                this.GetFosaStatementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFosaStatementOperationCompleted);
            }
            this.InvokeAsync("GetFosaStatement", new object[] {
                        account}, this.GetFosaStatementOperationCompleted, userState);
        }
        
        private void OnGetFosaStatementOperationCompleted(object arg) {
            if ((this.GetFosaStatementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFosaStatementCompleted(this, new GetFosaStatementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTransactionMinAmount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal GetTransactionMinAmount() {
            object[] results = this.Invoke("GetTransactionMinAmount", new object[0]);
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void GetTransactionMinAmountAsync() {
            this.GetTransactionMinAmountAsync(null);
        }
        
        /// <remarks/>
        public void GetTransactionMinAmountAsync(object userState) {
            if ((this.GetTransactionMinAmountOperationCompleted == null)) {
                this.GetTransactionMinAmountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransactionMinAmountOperationCompleted);
            }
            this.InvokeAsync("GetTransactionMinAmount", new object[0], this.GetTransactionMinAmountOperationCompleted, userState);
        }
        
        private void OnGetTransactionMinAmountOperationCompleted(object arg) {
            if ((this.GetTransactionMinAmountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTransactionMinAmountCompleted(this, new GetTransactionMinAmountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTransactionMaxAmount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal GetTransactionMaxAmount() {
            object[] results = this.Invoke("GetTransactionMaxAmount", new object[0]);
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void GetTransactionMaxAmountAsync() {
            this.GetTransactionMaxAmountAsync(null);
        }
        
        /// <remarks/>
        public void GetTransactionMaxAmountAsync(object userState) {
            if ((this.GetTransactionMaxAmountOperationCompleted == null)) {
                this.GetTransactionMaxAmountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransactionMaxAmountOperationCompleted);
            }
            this.InvokeAsync("GetTransactionMaxAmount", new object[0], this.GetTransactionMaxAmountOperationCompleted, userState);
        }
        
        private void OnGetTransactionMaxAmountOperationCompleted(object arg) {
            if ((this.GetTransactionMaxAmountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTransactionMaxAmountCompleted(this, new GetTransactionMaxAmountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTariffCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTariffCode(string type) {
            object[] results = this.Invoke("GetTariffCode", new object[] {
                        type});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTariffCodeAsync(string type) {
            this.GetTariffCodeAsync(type, null);
        }
        
        /// <remarks/>
        public void GetTariffCodeAsync(string type, object userState) {
            if ((this.GetTariffCodeOperationCompleted == null)) {
                this.GetTariffCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTariffCodeOperationCompleted);
            }
            this.InvokeAsync("GetTariffCode", new object[] {
                        type}, this.GetTariffCodeOperationCompleted, userState);
        }
        
        private void OnGetTariffCodeOperationCompleted(object arg) {
            if ((this.GetTariffCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTariffCodeCompleted(this, new GetTariffCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetWithdrawalCharges", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal GetWithdrawalCharges(string type, decimal amount) {
            object[] results = this.Invoke("GetWithdrawalCharges", new object[] {
                        type,
                        amount});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void GetWithdrawalChargesAsync(string type, decimal amount) {
            this.GetWithdrawalChargesAsync(type, amount, null);
        }
        
        /// <remarks/>
        public void GetWithdrawalChargesAsync(string type, decimal amount, object userState) {
            if ((this.GetWithdrawalChargesOperationCompleted == null)) {
                this.GetWithdrawalChargesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWithdrawalChargesOperationCompleted);
            }
            this.InvokeAsync("GetWithdrawalCharges", new object[] {
                        type,
                        amount}, this.GetWithdrawalChargesOperationCompleted, userState);
        }
        
        private void OnGetWithdrawalChargesOperationCompleted(object arg) {
            if ((this.GetWithdrawalChargesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWithdrawalChargesCompleted(this, new GetWithdrawalChargesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCharges", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal GetCharges(string type) {
            object[] results = this.Invoke("GetCharges", new object[] {
                        type});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void GetChargesAsync(string type) {
            this.GetChargesAsync(type, null);
        }
        
        /// <remarks/>
        public void GetChargesAsync(string type, object userState) {
            if ((this.GetChargesOperationCompleted == null)) {
                this.GetChargesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChargesOperationCompleted);
            }
            this.InvokeAsync("GetCharges", new object[] {
                        type}, this.GetChargesOperationCompleted, userState);
        }
        
        private void OnGetChargesOperationCompleted(object arg) {
            if ((this.GetChargesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChargesCompleted(this, new GetChargesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PostAgentTransaction", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PostAgentTransaction(string refrence) {
            object[] results = this.Invoke("PostAgentTransaction", new object[] {
                        refrence});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PostAgentTransactionAsync(string refrence) {
            this.PostAgentTransactionAsync(refrence, null);
        }
        
        /// <remarks/>
        public void PostAgentTransactionAsync(string refrence, object userState) {
            if ((this.PostAgentTransactionOperationCompleted == null)) {
                this.PostAgentTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostAgentTransactionOperationCompleted);
            }
            this.InvokeAsync("PostAgentTransaction", new object[] {
                        refrence}, this.PostAgentTransactionOperationCompleted, userState);
        }
        
        private void OnPostAgentTransactionOperationCompleted(object arg) {
            if ((this.PostAgentTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostAgentTransactionCompleted(this, new PostAgentTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PostBranchAgentTransaction", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PostBranchAgentTransaction(string refrence) {
            object[] results = this.Invoke("PostBranchAgentTransaction", new object[] {
                        refrence});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PostBranchAgentTransactionAsync(string refrence) {
            this.PostBranchAgentTransactionAsync(refrence, null);
        }
        
        /// <remarks/>
        public void PostBranchAgentTransactionAsync(string refrence, object userState) {
            if ((this.PostBranchAgentTransactionOperationCompleted == null)) {
                this.PostBranchAgentTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostBranchAgentTransactionOperationCompleted);
            }
            this.InvokeAsync("PostBranchAgentTransaction", new object[] {
                        refrence}, this.PostBranchAgentTransactionOperationCompleted, userState);
        }
        
        private void OnPostBranchAgentTransactionOperationCompleted(object arg) {
            if ((this.PostBranchAgentTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostBranchAgentTransactionCompleted(this, new PostBranchAgentTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertMessages", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertMessages(string refrence, string Telephone, string text) {
            object[] results = this.Invoke("InsertMessages", new object[] {
                        refrence,
                        Telephone,
                        text});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertMessagesAsync(string refrence, string Telephone, string text) {
            this.InsertMessagesAsync(refrence, Telephone, text, null);
        }
        
        /// <remarks/>
        public void InsertMessagesAsync(string refrence, string Telephone, string text, object userState) {
            if ((this.InsertMessagesOperationCompleted == null)) {
                this.InsertMessagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertMessagesOperationCompleted);
            }
            this.InvokeAsync("InsertMessages", new object[] {
                        refrence,
                        Telephone,
                        text}, this.InsertMessagesOperationCompleted, userState);
        }
        
        private void OnInsertMessagesOperationCompleted(object arg) {
            if ((this.InsertMessagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertMessagesCompleted(this, new InsertMessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertAgencyTransaction", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertAgencyTransaction(
                    string reference, 
                    string account_1, 
                    string description, 
                    decimal amount, 
                    string account_2, 
                    string trans_code, 
                    string agent_code, 
                    string loan_no, 
                    string Account_Name, 
                    string Telephone, 
                    string id_no, 
                    int transactiontype, 
                    string branch, 
                    System.DateTime Dob, 
                    string address, 
                    string PhysicallAddress, 
                    string postalcode, 
                    string residence) {
            object[] results = this.Invoke("InsertAgencyTransaction", new object[] {
                        reference,
                        account_1,
                        description,
                        amount,
                        account_2,
                        trans_code,
                        agent_code,
                        loan_no,
                        Account_Name,
                        Telephone,
                        id_no,
                        transactiontype,
                        branch,
                        Dob,
                        address,
                        PhysicallAddress,
                        postalcode,
                        residence});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertAgencyTransactionAsync(
                    string reference, 
                    string account_1, 
                    string description, 
                    decimal amount, 
                    string account_2, 
                    string trans_code, 
                    string agent_code, 
                    string loan_no, 
                    string Account_Name, 
                    string Telephone, 
                    string id_no, 
                    int transactiontype, 
                    string branch, 
                    System.DateTime Dob, 
                    string address, 
                    string PhysicallAddress, 
                    string postalcode, 
                    string residence) {
            this.InsertAgencyTransactionAsync(reference, account_1, description, amount, account_2, trans_code, agent_code, loan_no, Account_Name, Telephone, id_no, transactiontype, branch, Dob, address, PhysicallAddress, postalcode, residence, null);
        }
        
        /// <remarks/>
        public void InsertAgencyTransactionAsync(
                    string reference, 
                    string account_1, 
                    string description, 
                    decimal amount, 
                    string account_2, 
                    string trans_code, 
                    string agent_code, 
                    string loan_no, 
                    string Account_Name, 
                    string Telephone, 
                    string id_no, 
                    int transactiontype, 
                    string branch, 
                    System.DateTime Dob, 
                    string address, 
                    string PhysicallAddress, 
                    string postalcode, 
                    string residence, 
                    object userState) {
            if ((this.InsertAgencyTransactionOperationCompleted == null)) {
                this.InsertAgencyTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertAgencyTransactionOperationCompleted);
            }
            this.InvokeAsync("InsertAgencyTransaction", new object[] {
                        reference,
                        account_1,
                        description,
                        amount,
                        account_2,
                        trans_code,
                        agent_code,
                        loan_no,
                        Account_Name,
                        Telephone,
                        id_no,
                        transactiontype,
                        branch,
                        Dob,
                        address,
                        PhysicallAddress,
                        postalcode,
                        residence}, this.InsertAgencyTransactionOperationCompleted, userState);
        }
        
        private void OnInsertAgencyTransactionOperationCompleted(object arg) {
            if ((this.InsertAgencyTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertAgencyTransactionCompleted(this, new InsertAgencyTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void AgencyRegistrationCompletedEventHandler(object sender, AgencyRegistrationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgencyRegistrationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgencyRegistrationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void UpdateAgencyRegistrationCompletedEventHandler(object sender, UpdateAgencyRegistrationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateAgencyRegistrationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateAgencyRegistrationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void accountlistCompletedEventHandler(object sender, accountlistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class accountlistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal accountlistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetLoansCompletedEventHandler(object sender, GetLoansCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLoansCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLoansCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetAccountsCompletedEventHandler(object sender, GetAccountsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetMemberCompletedEventHandler(object sender, GetMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetMiniStatementCompletedEventHandler(object sender, GetMiniStatementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMiniStatementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMiniStatementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetAccountInfoCompletedEventHandler(object sender, GetAccountInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetwithdrawableAccCompletedEventHandler(object sender, GetwithdrawableAccCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetwithdrawableAccCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetwithdrawableAccCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetAccountBalanceCompletedEventHandler(object sender, GetAccountBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetAgentFloatCompletedEventHandler(object sender, GetAgentFloatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAgentFloatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAgentFloatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetAgentAccountCompletedEventHandler(object sender, GetAgentAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAgentAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAgentAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetAccountExistCompletedEventHandler(object sender, GetAccountExistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountExistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountExistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetAgentTransactionCompletedEventHandler(object sender, GetAgentTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAgentTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAgentTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetLoanStatementCompletedEventHandler(object sender, GetLoanStatementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLoanStatementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLoanStatementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetFosaStatementCompletedEventHandler(object sender, GetFosaStatementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFosaStatementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFosaStatementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetTransactionMinAmountCompletedEventHandler(object sender, GetTransactionMinAmountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTransactionMinAmountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTransactionMinAmountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetTransactionMaxAmountCompletedEventHandler(object sender, GetTransactionMaxAmountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTransactionMaxAmountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTransactionMaxAmountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetTariffCodeCompletedEventHandler(object sender, GetTariffCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTariffCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTariffCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetWithdrawalChargesCompletedEventHandler(object sender, GetWithdrawalChargesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWithdrawalChargesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWithdrawalChargesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetChargesCompletedEventHandler(object sender, GetChargesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChargesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChargesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void PostAgentTransactionCompletedEventHandler(object sender, PostAgentTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostAgentTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostAgentTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void PostBranchAgentTransactionCompletedEventHandler(object sender, PostBranchAgentTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostBranchAgentTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostBranchAgentTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void InsertMessagesCompletedEventHandler(object sender, InsertMessagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void InsertAgencyTransactionCompletedEventHandler(object sender, InsertAgencyTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertAgencyTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertAgencyTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591